#!/bin/sh

# Generate HTML pages from the specifications.

not_specs='render|readme|software'
specs=$(find . -maxdepth 1 -type f | grep -Ev $not_specs | sed 's/\.\///')

rm -rf docs/spec
mkdir -p docs/spec

for spec in $specs; do
    num=$(echo $spec | awk -F '-' '{ print $(NF) }')
    p=docs/rsd/$num.html
    echo Generating $p
    cat docs/_head.html | sed "s/((RSD_NUM))/$num/" > $p
    echo '<h2>' >> $p
    cat $spec | head -n 1 >> $p
    echo '</h2>\n<p>' >> $p

    cat $spec | tail -n +4  |\
        sed 's/\&/\&amp;/g' |\
        sed 's/</\&lt;/g'   |\
        sed 's/>/\&gt;/g'   |\
        sed 's/&lt;\(https*:\/\/.*\)&gt;/<a href="\1">\1<\/a>/' >> $p
    cat docs/_foot.html >> $p
done

echo "Generating docs/software.html"

# Set the software.html page
cat docs/_software_head.html > docs/software.html
echo '<p><b>' >> docs/software.html
cat software | head -n 1 >> docs/software.html
echo '</b></p><p>' >> docs/software.html
cat software | tail -n +3   |\
    sed 's/\&/\&amp;/g'     |\
    sed 's/</\&lt;/g'       |\
    sed 's/>/\&gt;/g'       |\
    sed 's/&lt;\(https*:\/\/.*\)&gt;/<a href="\1">\1<\/a>/g' >> docs/software.html
cat docs/_software_foot.html >> docs/software.html
